### ISSUE TITLE
2024.06.2 crash `locale.Error: unsupported locale setting`

### ISSUE THREAD

**Issue by Anto79-ops** [bachya/ecowitt2mqtt#1019]
hey thanks for the update!

I noticed some new feature with Locale, unfortunalty, its crashing my instance with this log error.

Am I supposed to add something to make it work?

cheers 

```
pi@raspberrypi:~ $ ecowitt2mqtt --mqtt-broker=192.168.1.154 --output-unit-system metric --mqtt-retain --hass-discovery --precision 2 -v
2024-06-21 15:41:26,030 | DEBUG | Input CLI options/environment variables: {'mqtt_broker': '192.168.1.154', 'output_unit_system': 'metric', 'mqtt_retain': True, 'hass_discovery': True, 'precision': '2', 'verbose': True}
2024-06-21 15:41:26,031 | DEBUG | Configs loaded: <Configs _configs={'default': Config(mqtt_broker='192.168.1.154', mqtt_password=None, mqtt_port=1883, mqtt_retain=True, mqtt_tls=False, mqtt_topic=None, mqtt_username=None, battery_overrides={}, boolean_battery_true_value=1, default_battery_strategy=<BatteryStrategy.BOOLEAN: 'boolean'>, disable_calculated_data=False, input_data_format=<InputDataFormat.ECOWITT: 'ecowitt'>, precision=2, raw_data=False, hass_discovery=True, hass_discovery_prefix='homeassistant', hass_entity_id_prefix=None, endpoint='/data/report', port=8080, diagnostics=False, verbose=True, output_unit_accumulated_precipitation=None, output_unit_distance=None, output_unit_humidity=None, output_unit_illuminance=None, output_unit_precipitation_rate=None, output_unit_pressure=None, output_unit_speed=None, output_unit_temperature=None, input_unit_system=<UnitSystem.IMPERIAL: 'imperial'>, output_unit_system=<UnitSystem.METRIC: 'metric'>, uuid='[redacated]', locale='en_US.UTF-8')}
2024-06-21 15:41:26,031 | DEBUG | Setting locale: en_US.UTF-8
Traceback (most recent call last):
  File "/usr/local/bin/ecowitt2mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ecowitt2mqtt/__main__.py", line 423, in main
    ecowitt = Ecowitt(env_vars | cli_arguments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 67, in __init__
    locale.setlocale(locale.LC_ALL, self.configs.default_config.locale)
  File "/usr/local/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting

```

**Comment by Anto79-ops** [comment]
ok turns out that `en_US.UTF-8` was not listed in my locales. so I followed this guide to add it, and it worked!

https://linuxconfig.org/how-to-set-locale-on-raspberry-pi
