### ISSUE TITLE
Locale Error

### ISSUE THREAD

**Issue by riodda** [bachya/ecowitt2mqtt#1026]
**Describe the bug**

Locale Error

```
root@apu-chieam:/home/ipergola# ecowitt2mqtt -c /home/ipergola/ecowitt2mqtt/config.yaml
2024-06-28 10:43:37,104 | DEBUG | Input CLI options/environment variables: {'config': '/home/ipergola/ecowitt2mqtt/config.yaml'}
2024-06-28 10:43:37,106 | DEBUG | Configs loaded: <Configs _configs={'default': Config(mqtt_broker='192.168.104.28', mqtt_password='ipergolamqtt', mqtt_port=1883, mqtt_retain=True, mqtt_tls=False, mqtt_topic='meteo', mqtt_username='plc', battery_overrides={}, boolean_battery_true_value=1, default_battery_strategy=<BatteryStrategy.BOOLEAN: 'boolean'>, disable_calculated_data=True, input_data_format=<InputDataFormat.ECOWITT: 'ecowitt'>, precision=None, raw_data=False, hass_discovery=True, hass_discovery_prefix='weather_station', hass_entity_id_prefix='sensor', endpoint='/data/report', port=8080, diagnostics=False, verbose=True, output_unit_accumulated_precipitation=None, output_unit_distance=None, output_unit_humidity=None, output_unit_illuminance=None, output_unit_precipitation_rate=None, output_unit_pressure=None, output_unit_speed=None, output_unit_temperature=None, input_unit_system=<UnitSystem.IMPERIAL: 'imperial'>, output_unit_system=<UnitSystem.METRIC: 'metric'>, uuid='89abe1f57f784e8899162bfb881cb995', locale='en_US.UTF-8')}
2024-06-28 10:43:37,107 | DEBUG | Setting locale: en_US.UTF-8
Traceback (most recent call last):
  File "/root/.local/bin/ecowitt2mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/pipx/venvs/ecowitt2mqtt/lib/python3.11/site-packages/ecowitt2mqtt/__main__.py", line 423, in main
    ecowitt = Ecowitt(env_vars | cli_arguments)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/ecowitt2mqtt/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 67, in __init__
    locale.setlocale(locale.LC_ALL, self.configs.default_config.locale)
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
```

**To Reproduce**
Setup Debian 12 out of the box, install ecowitt2mqtt with pipx

**Expected behavior**
Software start

**Screenshots**

**Additional context**
```
root@apu-chieam:/home/ipergola# export LC_ALL=en_GB.UTF-8
root@apu-chieam:/home/ipergola# locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

**Comment by riodda** [comment]
I've installed all the locales, now i have this error:

`root@apu-chieam:/home/ipergola# ecowitt2mqtt \
    --mqtt-broker=192.168.104.26 \
    --mqtt-username=plc \
    --mqtt-password=ipergolamqtt \
    --mqtt-topic=ecowitt2mqtt/device_1
    --input-data-format=ecowitt
2024-06-28 11:02:19,441 | INFO | Starting ecowitt2mqtt (version 2024.06.2)
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
bash: --input-data-format=ecowitt: command not found
`

**Comment by bachya** [comment]
Your first error is caused by your Debian instance missing the default locale used by `ecowitt2mqtt`. Once you installed that locale, the error went away. I've seen this before, which makes me realize we shouldn't set any locale unless one is explicitly provided. I'll work on a PR for that.

Your second error is a combination of a missing slash after your MQTT topic and something already using port 8080 on your device.
