### ISSUE TITLE
Lightning "last strike distance" sensor breaks on empty string

### ISSUE THREAD

**Issue by ketilmo** [bachya/ecowitt2mqtt#121]
**ecowitt2mqtt version**
2022.04.1

**Describe the bug**
Thanks for working on the lightning sensor issue. After updating to the newest release, I still see issues, unfortunately. Please see the logs below.

**Logs**
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/mqtt.py", line 89, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 160, in generate_data
    output = calculate()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 57, in <lambda>
    DATA_POINT_LIGHTNING: lambda val: calculate_distance(
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/util/distance.py", line 14, in calculate_distance
    float_value = float(value)
ValueError: could not convert string to float: ''
INFO:aiohttp.access:192.168.56.130 [23/Apr/2022:09:56:50 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

**Comment by ketilmo** [comment]
I should add that I'm running ecowitt2mqtt through Daniel Hall's Home Assistant Docker module: https://github.com/smarthall/hassio-addons/

**Comment by bachya** [comment]
Wow, so the lightning strike distance arrives as an empty string...? 😲  I guess I can "fix" that by catching any `ValueError` and returning `None`.

**Comment by ketilmo** [comment]
Thanks, @bachya, it’s appreciated.

**Comment by ketilmo** [comment]
Hi @bachya,

Would it be possible for you to cut a new release that includes this fix? Daniel Hall's Docker module uses the release number to fetch the most recent released version of this repo.

**Comment by bachya** [comment]
I will once I track https://github.com/bachya/ecowitt2mqtt/issues/120 down.

**Comment by ketilmo** [comment]
Thanks @bachya
