### ISSUE TITLE
TypeError: an integer is required (got type str)

### ISSUE THREAD

**Issue by ketilmo** [bachya/ecowitt2mqtt#128]
Hi,

After upgrading to version 2022.04.03 (via @SmartHalls’ plugin), I get the following error message in the logs.

**ecowitt2mqtt version**
2022.04.3

**Log output**
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/mqtt.py", line 95, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 160, in generate_data
    output = calculate()
  File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/util/time.py", line 7, in calculate_epoch
    return datetime.utcfromtimestamp(value).replace(tzinfo=timezone.utc)
TypeError: an integer is required (got type str)
INFO:aiohttp.access:192.168.1.13
[02/May/2022:04:26:15 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

**Comment by bachya** [comment]
Can you set your logs to `DEBUG`-level and share? I want to see what the raw value looks like.

**Comment by moesizlag** [comment]
I got the same error, here's the log output:

`DEBUG:ecowitt2mqtt:Received data from Ecowitt device: {'PASSKEY': '--removed--', 'stationtype': 'GW2000A_V2.1.4', 'runtime': '3179', 'dateutc': '2022-05-18 18:17:37', 'tempinf': '71.2', 'humidityin': '49', 'baromrelin': '28.476', 'baromabsin': '28.476', 'tempf': '74.5', 'humidity': '47', 'winddir': '100', 'windspeedmph': '1.34', 'windgustmph': '2.24', 'maxdailygust': '2.24', 'solarradiation': '0.00', 'uv': '0', 'rrain_piezo': '0.000', 'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000', 'ws90cap_volt': '0.6', 'ws90_ver': '119', 'lightning_num': '1', 'lightning': '27', 'lightning_time': '', 'wh57batt': '5', 'wh90batt': '3.16', 'freq': '868M', 'model': 'GW2000A'}
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/dist-packages/ecowitt2mqtt/mqtt.py", line 95, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/local/lib/python3.8/dist-packages/ecowitt2mqtt/data.py", line 160, in generate_data
    output = calculate()
  File "/usr/local/lib/python3.8/dist-packages/ecowitt2mqtt/util/time.py", line 7, in calculate_epoch
    return datetime.utcfromtimestamp(value).replace(tzinfo=timezone.utc)
TypeError: an integer is required (got type str)
INFO:aiohttp.access:192.168.30.156 [18/May/2022:18:17:37 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
`

**Comment by bachya** [comment]
Thanks for the info, @moesizlag. The data in question is here:

```
'lightning_time': ''
```

This indicates that lightning sensors don't always return the time of the last strike; so, `ecowitt2mqtt` can't make that assumption.

**Comment by moesizlag** [comment]
Thanks for the prompt reply @bachya 
I just received the weather station today and have no idea if / how accurate this field will be filled when strikes are recognized. And while I was typing my suggestion you already created a PR ;) 
Thx !!

**Comment by bachya** [comment]
Happy to help, @moesizlag!

**Comment by ketilmo** [comment]
Thanks, @bachya! It’s appreciated. And apologies for the late feedback from me. I hadn’t yet got around to turn around verbose logging in the dockerized add on, but am happy that @moesizlag came to the rescue here. Thanks again and keep up the great work!
