### ISSUE TITLE
Can't build docker image

### ISSUE THREAD

**Issue by fspralja** [bachya/ecowitt2mqtt#13]
Hi, was about to add additional temperature sensors (temp1f, temp2f,..._) but run into two issues:

after building the docker image and running I get following error:

```
2020-10-24 17:15:01,312 INFO Set uid to user 0 succeeded
2020-10-24 17:15:01,318 INFO supervisord started with pid 7
2020-10-24 17:15:02,321 INFO spawned: 'ecowitt2mqtt' with pid 9
Traceback (most recent call last):
  File "/usr/local/bin/ecowitt2mqtt", line 33, in <module>
    sys.exit(load_entry_point('ecowitt2mqtt', 'console_scripts', 'ecowitt2mqtt')())
  File "/usr/local/bin/ecowitt2mqtt", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/ecowitt2mqtt/main.py", line 5, in <module>
    from aiohttp import web
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web.py", line 23, in <module>
    from .web_app import Application as Application
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 39, in <module>
    from .web_middlewares import _fix_request_current_app
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 7, in <module>
    from .web_urldispatcher import SystemRoute
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 36, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

maybe some specific docker build command or something else I'm missing?

Later tried with venv on linux host but script/setup results in following error:

```
Updating dependencies
Resolving dependencies... (71.4s)

Writing lock file
Installing dependencies from lock file

Package operations: 15 installs, 1 update, 0 removals

  • Updating importlib-metadata (1.7.0 -> 2.0.0)
  • Installing multidict (4.7.6)
  • Installing typing-extensions (3.7.4.3)
  • Installing async-timeout (3.0.1)
  • Installing attrs (20.2.0)
  • Installing cfgv (3.2.0)
  • Installing identify (1.5.6)
  • Installing nodeenv (1.5.0)
  • Installing paho-mqtt (1.5.1)
  • Installing pyyaml (5.3.1)
  • Installing toml (0.10.1)
  • Installing yarl (1.6.2): Failed

  EnvCommandError

  Command ['/opt/ecowitt2mqtt/.venv/bin/pip', 'install', '--no-deps', '/root/.cache/pypoetry/artifacts/26/9a/6e/cfbeac5168ae43212e555f36d281df19dfbb681804f5b15e02e74b7da7/yarl-1.6.2-cp37-cp37m-manylinux2014_x86_64.whl'] errored with the following return code 1, and output: 
  yarl-1.6.2-cp37-cp37m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

any hints on how to resolve those setup issues would be nice, ty

**Comment by bachya** [comment]
What OS are you building the Docker image on?

**Comment by fspralja** [comment]
debian buster

**Comment by bachya** [comment]
I just spun up a Debian Buster (64-bit) VM and was able to build the image without issue:

```bash
$ git clone https://github.com/bachya/ecowitt2mqtt.git
$ cd ecowitt2mqtt/
$ docker build -t bachya/ecowitt2mqtt:test .

Sending build context to Docker daemon  636.9kB
Step 1/9 : FROM python:alpine3.12
alpine3.12: Pulling from library/python
188c0c94c7c5: Pull complete
55578f60cda7: Pull complete
692da2fcb614: Pull complete
599e2857d4f0: Pull complete
4b3bf1abad55: Pull complete
Digest: sha256:8a7556174f0c9841df1a85ebe1e221f0151c825574370fa0580d5800ad4fca24
Status: Downloaded newer image for python:alpine3.12
 ---> dc68588b1801
Step 2/9 : COPY README.md /usr/src/README.md
 ---> fb5268dac5f6
Step 3/9 : COPY ecowitt2mqtt /usr/src/ecowitt2mqtt
 ---> 20fdd796c14c
Step 4/9 : COPY pyproject.toml /usr/src/pyproject.toml
 ---> 1693a68d1582
Step 5/9 : WORKDIR /usr/src
 ---> Running in 6f2450502687
Removing intermediate container 6f2450502687
 ---> 9bd0325d8026
Step 6/9 : RUN apk add --no-cache --virtual build-dependencies       build-base==0.5-r2       libffi-dev==3.3-r2       openssl-dev==1.1.1g-r0     && apk add --no-cache       supervisor==4.2.0-r0     && pip3 install poetry==1.0.10     && poetry config virtualenvs.create false     && poetry lock && poetry install --no-dev     && pip3 uninstall -y poetry     && apk del build-dependencies
 ---> Running in 381cf330560a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/25) Installing libgcc (9.3.0-r2)
(2/25) Installing libstdc++ (9.3.0-r2)
(3/25) Installing binutils (2.34-r1)
(4/25) Installing libmagic (5.38-r0)
(5/25) Installing file (5.38-r0)
(6/25) Installing gmp (6.2.0-r0)
(7/25) Installing isl (0.18-r0)
(8/25) Installing libgomp (9.3.0-r2)
(9/25) Installing libatomic (9.3.0-r2)
(10/25) Installing libgphobos (9.3.0-r2)
(11/25) Installing mpfr4 (4.0.2-r4)
(12/25) Installing mpc1 (1.1.0-r1)
(13/25) Installing gcc (9.3.0-r2)
(14/25) Installing musl-dev (1.1.24-r9)
(15/25) Installing libc-dev (0.7.2-r3)
(16/25) Installing g++ (9.3.0-r2)
(17/25) Installing make (4.3-r0)
(18/25) Installing fortify-headers (1.1-r0)
(19/25) Installing patch (2.7.6-r6)
(20/25) Installing build-base (0.5-r2)
(21/25) Installing linux-headers (5.4.5-r1)
(22/25) Installing pkgconf (1.7.2-r0)
(23/25) Installing libffi-dev (3.3-r2)
(24/25) Installing openssl-dev (1.1.1g-r0)
(25/25) Installing build-dependencies (20201025.195821)
Executing busybox-1.31.1-r19.trigger
OK: 220 MiB in 60 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/9) Installing python3 (3.8.5-r0)
(2/9) Installing py3-meld3 (2.0.1-r0)
(3/9) Installing py3-ordered-set (4.0.1-r0)
(4/9) Installing py3-appdirs (1.4.4-r1)
(5/9) Installing py3-parsing (2.4.7-r0)
(6/9) Installing py3-six (1.15.0-r0)
(7/9) Installing py3-packaging (20.4-r0)
(8/9) Installing py3-setuptools (47.0.0-r0)
(9/9) Installing supervisor (4.2.0-r0)
Executing busybox-1.31.1-r19.trigger
OK: 272 MiB in 69 packages
Collecting poetry==1.0.10
  Downloading poetry-1.0.10-py2.py3-none-any.whl (224 kB)
Collecting requests-toolbelt<0.9.0,>=0.8.0
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54 kB)
Collecting cachecontrol[filecache]<0.13.0,>=0.12.4
  Downloading CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)
Collecting keyring<21.0.0,>=20.0.1; python_version >= "3.5" and python_version < "4.0"
  Downloading keyring-20.0.1-py2.py3-none-any.whl (31 kB)
Collecting html5lib<2.0,>=1.0
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting jsonschema<4.0,>=3.1
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting pyrsistent<0.15.0,>=0.14.2
  Downloading pyrsistent-0.14.11.tar.gz (104 kB)
Collecting pkginfo<2.0,>=1.4
  Downloading pkginfo-1.6.0-py2.py3-none-any.whl (25 kB)
Collecting tomlkit<0.6.0,>=0.5.11
  Downloading tomlkit-0.5.11-py2.py3-none-any.whl (31 kB)
Collecting pyparsing<3.0,>=2.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting clikit<0.5.0,>=0.4.2
  Downloading clikit-0.4.3-py2.py3-none-any.whl (88 kB)
Collecting cachy<0.4.0,>=0.3.0
  Downloading cachy-0.3.0-py2.py3-none-any.whl (20 kB)
Collecting requests<3.0,>=2.18
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting pexpect<5.0.0,>=4.7.0
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting shellingham<2.0,>=1.1
  Downloading shellingham-1.3.2-py2.py3-none-any.whl (11 kB)
Collecting cleo<0.8.0,>=0.7.6
  Downloading cleo-0.7.6-py2.py3-none-any.whl (21 kB)
Collecting msgpack>=0.5.2
  Downloading msgpack-1.0.0.tar.gz (232 kB)
Collecting lockfile>=0.9; extra == "filecache"
  Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting secretstorage; sys_platform == "linux"
  Downloading SecretStorage-3.1.2-py3-none-any.whl (14 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting six>=1.9
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from jsonschema<4.0,>=3.1->poetry==1.0.10) (50.3.2)
Collecting attrs>=17.4.0
  Downloading attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting pylev<2.0,>=1.3
  Downloading pylev-1.3.0-py2.py3-none-any.whl (4.9 kB)
Collecting pastel<0.3.0,>=0.2.0
  Downloading pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting cryptography
  Downloading cryptography-3.1.1.tar.gz (534 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting jeepney>=0.4.2
  Downloading jeepney-0.4.3-py3-none-any.whl (21 kB)
Processing /root/.cache/pip/wheels/7d/c3/97/992a1470f19e64685156eefd4259e6702e62b9203d7f865087/cffi-1.14.3-cp39-cp39-linux_x86_64.whl
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: pyrsistent, msgpack, cryptography
  Building wheel for pyrsistent (setup.py): started
  Building wheel for pyrsistent (setup.py): finished with status 'done'
  Created wheel for pyrsistent: filename=pyrsistent-0.14.11-cp39-cp39-linux_x86_64.whl size=72195 sha256=90f175ca7ad176dbe8b034b55c1c9c7a93a773c0ddf3bbec252ca4c8e98c0125
  Stored in directory: /root/.cache/pip/wheels/8d/ac/97/0084b3abfdf6380ea73ef4e20938872fd2dd7e0b6932c1532b
  Building wheel for msgpack (setup.py): started
  Building wheel for msgpack (setup.py): finished with status 'done'
  Created wheel for msgpack: filename=msgpack-1.0.0-cp39-cp39-linux_x86_64.whl size=85112 sha256=4a8b8d52823ea4449795f6d4c4e1cc79dccda58c06f9932056f1e6f282e31417
  Stored in directory: /root/.cache/pip/wheels/2f/1d/87/e0bdd7bbc2b61c8b78c4ed78964ab8f6f88456156a24d3e079
  Building wheel for cryptography (PEP 517): started
  Building wheel for cryptography (PEP 517): finished with status 'done'
  Created wheel for cryptography: filename=cryptography-3.1.1-cp39-cp39-linux_x86_64.whl size=356315 sha256=96c0d1ae7395746f21ab93c338e4fdc58e2347a68dcc062d25434a051723ae61
  Stored in directory: /root/.cache/pip/wheels/72/4c/4f/556bd5800edef5f605432cc0b7705ba777ca5feaac0c80b86e
Successfully built pyrsistent msgpack cryptography
Installing collected packages: chardet, certifi, idna, urllib3, requests, requests-toolbelt, msgpack, lockfile, cachecontrol, pycparser, cffi, six, cryptography, jeepney, secretstorage, keyring, webencodings, html5lib, attrs, pyrsistent, jsonschema, pkginfo, tomlkit, pyparsing, pylev, pastel, clikit, cachy, ptyprocess, pexpect, shellingham, cleo, poetry
Successfully installed attrs-20.2.0 cachecontrol-0.12.6 cachy-0.3.0 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cleo-0.7.6 clikit-0.4.3 cryptography-3.1.1 html5lib-1.1 idna-2.10 jeepney-0.4.3 jsonschema-3.2.0 keyring-20.0.1 lockfile-0.12.2 msgpack-1.0.0 pastel-0.2.1 pexpect-4.8.0 pkginfo-1.6.0 poetry-1.0.10 ptyprocess-0.6.0 pycparser-2.20 pylev-1.3.0 pyparsing-2.4.7 pyrsistent-0.14.11 requests-2.24.0 requests-toolbelt-0.8.0 secretstorage-3.1.2 shellingham-1.3.2 six-1.15.0 tomlkit-0.5.11 urllib3-1.25.11 webencodings-0.5.1
Skipping virtualenv creation, as specified in config file.
Updating dependencies
Resolving dependencies...

Writing lock file
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file


Package operations: 8 installs, 0 updates, 1 removal

  - Installing multidict (5.0.0)
  - Installing async-timeout (3.0.1)
  - Installing paho-mqtt (1.5.1)
  - Installing typing-extensions (3.7.4.3)
  - Installing yarl (1.6.2)
  - Installing aiohttp (3.7.1)
  - Installing asyncio-mqtt (0.7.0)
  - Installing meteocalc (1.1.0)
  - Removing six (1.15.0)
  - Installing ecowitt2mqtt (0.1.1)
Found existing installation: poetry 1.0.10
Uninstalling poetry-1.0.10:
  Successfully uninstalled poetry-1.0.10
(1/25) Purging build-dependencies (20201025.195821)
(2/25) Purging build-base (0.5-r2)
(3/25) Purging file (5.38-r0)
(4/25) Purging g++ (9.3.0-r2)
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
(5/25) Purging gcc (9.3.0-r2)
(6/25) Purging binutils (2.34-r1)
(7/25) Purging libatomic (9.3.0-r2)
(8/25) Purging libgomp (9.3.0-r2)
(9/25) Purging libgphobos (9.3.0-r2)
(10/25) Purging libstdc++ (9.3.0-r2)
(11/25) Purging make (4.3-r0)
(12/25) Purging libc-dev (0.7.2-r3)
(13/25) Purging musl-dev (1.1.24-r9)
(14/25) Purging fortify-headers (1.1-r0)
(15/25) Purging patch (2.7.6-r6)
(16/25) Purging libffi-dev (3.3-r2)
(17/25) Purging linux-headers (5.4.5-r1)
(18/25) Purging openssl-dev (1.1.1g-r0)
(19/25) Purging libgcc (9.3.0-r2)
(20/25) Purging libmagic (5.38-r0)
(21/25) Purging isl (0.18-r0)
(22/25) Purging mpc1 (1.1.0-r1)
(23/25) Purging mpfr4 (4.0.2-r4)
(24/25) Purging gmp (6.2.0-r0)
(25/25) Purging pkgconf (1.7.2-r0)
Executing busybox-1.31.1-r19.trigger
OK: 63 MiB in 44 packages
Removing intermediate container 381cf330560a
 ---> 88b89362fc47
Step 7/9 : COPY supervisord.conf /etc/supervisord.conf
 ---> 8b8feacc2233
Step 8/9 : COPY run.sh /usr/local/bin/run.sh
 ---> 516645862631
Step 9/9 : ENTRYPOINT ["/usr/local/bin/run.sh"]
 ---> Running in 5cd42d11e04b
Removing intermediate container 5cd42d11e04b
 ---> 2aa6c4bc88fd
Successfully built 2aa6c4bc88fd
Successfully tagged bachya/ecowitt2mqtt:test
```

I was then able to run the image just fine:

```bash
$ docker run -e MQTT_BROKER="..." -e MQTT_PASSWORD="..." -e MQTT_USER="..." -e MQTT_TOPIC="..." bachya/ecowitt2mqtt:test

2020-10-25 20:01:45,952 INFO Set uid to user 0 succeeded
2020-10-25 20:01:45,958 INFO supervisord started with pid 7
2020-10-25 20:01:46,975 INFO spawned: 'ecowitt2mqtt' with pid 9
2020-10-25 20:01:48,511 INFO success: ecowitt2mqtt entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by fspralja** [comment]
ok ty, will try buster vm, this is on a intel nuc x64

**Comment by fspralja** [comment]
It now built OK from osx and works fine with same codebase/commands.

Regarding the multiple temperature sensors, just added for now additional constants, or should this be resolved with regex/wildcard somehow?

anyways will test this and submit a merge request when its ready. tnx for now

**Comment by bachya** [comment]
@fspralja Feel free to submit your PR and I can offer feedback there. Closing this issue since you got the Docker image built. Thanks!
