### ISSUE TITLE
Exception caused a shutdown: 'hass_discovery_prefix'  in all 2022.09.XX  Rel

### ISSUE THREAD

**Issue by reba0** [bachya/ecowitt2mqtt#297]
```
28.09.2022 18:42:21
2022-09-28 16:42:21,969 | INFO | Starting ecowitt2mqtt (version 2022.09.0)
28.09.2022 18:43:31
2022-09-28 16:43:31,443 | ERROR | Exception caused a shutdown: 'hass_discovery_prefix'
28.09.2022 18:43:31
Traceback (most recent call last):
28.09.2022 18:43:31
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/runtime.py", line 116, in create_loop
28.09.2022 18:43:31
    await publisher.async_publish(payload)
28.09.2022 18:43:31
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 484, in async_publish
28.09.2022 18:43:31
    discovery_payload = self._generate_discovery_payload(
28.09.2022 18:43:31
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 426, in _generate_discovery_payload
28.09.2022 18:43:31
    f"{self._config.hass_discovery_prefix}/{PLATFORM_MAP[data_point.data_type]}"
28.09.2022 18:43:31
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/config.py", line 180, in hass_discovery_prefix
28.09.2022 18:43:31
    return cast(str, self._config[CONF_HASS_DISCOVERY_PREFIX])
28.09.2022 18:43:31
KeyError: 'hass_discovery_prefix'
28.09.2022 18:43:36
2022-09-28 16:43:36,065 | INFO | Starting ecowitt2mqtt (version 2022.09.0)
01.01.1970 1:00:00
Container stopped
```

**Comment by bachya** [comment]
Please provide your configuration.

**Comment by barcar** [comment]
I’m seeing this too. Here’s my config…

version: "3.5"
services:
  ecowitt2mqtt:
    image: bachya/ecowitt2mqtt:latest
    container_name: ecowitt2mqtt
    network_mode: host
    environment:
      - ECOWITT2MQTT_MQTT_BROKER=xxx.xxx
      - ECOWITT2MQTT_MQTT_PORT=1883
      - ECOWITT2MQTT_MQTT_PASSWORD=xxx
      - ECOWITT2MQTT_MQTT_USERNAME=xxx
      
      - ECOWITT2MQTT_HASS_DISCOVERY=false
      - ECOWITT2MQTT_MQTT_RETAIN=false
      
      - ECOWITT2MQTT_MQTT_TOPIC=climate/ecowitt
      
      - ECOWITT2MQTT_DISABLE_CALCULATE_DATA=true
      - ECOWITT2MQTT_INPUT_UNIT_SYSTEM=imperial
      - ECOWITT2MQTT_OUTPUT_UNIT_SYSTEM=metric
      - ECOWITT2MQTT_PORT=8078
      
      - ECOWITT2MQTT_DIAGNOSTICS=false
      - ECOWITT2MQTT_VERBOSE=true
      - TZ=Europe/London
    ports:
      - "8078:8078/tcp"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

**Comment by bachya** [comment]
Thanks for your config, @barcar. I am able to reproduce and will let you both know when I have more.
