### ISSUE TITLE
Sainlogic WS3500 (WS2900_V2.01.08) Data Issue

### ISSUE THREAD

**Issue by MarkThielen** [bachya/ecowitt2mqtt#32]
**ecowitt2mqtt version**
Latest Version, pulled via pip 20201212

**Describe the bug**
Configured Sainlogic WS3500 via WSView as described. 

Commandline used
```
 ecowitt2mqtt --mqtt-broker=homeassistant.fritz.box --mqtt-username=tasmota --mqtt-password=xxx --hass-discovery --unit-system metric -l DEBUG
```

Data is sent by the station and received by ecowitt2mqtt.
Debug output looks as follows.

 ```ecowitt2mqtt --mqtt-broker=homeassistant.fritz.box --mqtt-username=tasmota --mqtt-password=tasmota --hass-discovery --unit-system metric -l DEBUG
DEBUG:ecowitt2mqtt:Using arguments: Namespace(endpoint='/data/report', hass_discovery=True, hass_discovery_prefix=None, log_level='DEBUG', mqtt_broker='homeassistant.fritz.box', mqtt_password='tasmota', mqtt_port=1883, mqtt_topic=None, mqtt_username='tasmota', port=8080, unit_system='metric')
DEBUG:asyncio:Using selector: EpollSelector
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
```
Data is received and looks as follows

```
DEBUG:ecowitt2mqtt:Received data from Ecowitt device: {'PASSKEY': '641BC45267D8313205E7DC98CA552E6C', 'stationtype': 'EasyWeatherV1.5.6', 'dateutc': '2020-12-12 16:58:52', 'tempinf': '70.2', 'humidityin': '49', 'baromrelin': '29.616', 'baromabsin': '29.173', 'tempf': '41.7', 'humidity': '97', 'winddir': '313', 'windspeedmph': '0.0', 'windgustmph': '0.0', 'maxdailygust': '1.1', 'rainratein': '0.000', 'eventrainin': '0.213', 'hourlyrainin': '0.000', 'dailyrainin': '0.110', 'weeklyrainin': '0.453', 'monthlyrainin': '1.362', 'totalrainin': '22.051', 'solarradiation': '0.00', 'uv': '0', 'wh65batt': '0', 'freq': '868M', 'model': 'WS2900_V2.01.08'}
```
Error based on received data looks as follows
```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/ecowitt2mqtt/mqtt.py", line 85, in async_publish_payload
    data = data_processor.generate_data()
  File "/usr/local/lib/python3.7/dist-packages/ecowitt2mqtt/data.py", line 326, in generate_data
    pressure_data = self._generate_pressure_data()
  File "/usr/local/lib/python3.7/dist-packages/ecowitt2mqtt/data.py", line 208, in _generate_pressure_data
    data[new_key] = round(inhg_to_hpa(int(self._data[original_key])), 1)
ValueError: invalid literal for int() with base 10: '29.173'
INFO:aiohttp.access:192.168.2.129 [12/Dec/2020:17:02:05 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
```

**To Reproduce**
As described above with a Sainlogic WS3500 which seems to be a WS2900_V2.01.08 under to hood.

Everything seems to work fine but it seems like that the Station sends data as Strings but ecowitt2mqtt expects values sent as numbers (?). Maybe an issue with the station not sending the correct format ?

**Comment by MarkThielen** [comment]
I changed the following lines in `data.py` and it works now. I am sure there is a better way to handle this.

208:         data[new_key] = round(inhg_to_hpa(int(**float**(self._data[original_key]))), 1)
234:         data[new_key] = round(in_to_mm(int(**float**(self._data[original_key]))), 1)

**Comment by bachya** [comment]
Thanks, @MarkThielen!

**Comment by MarkThielen** [comment]
> Thanks, @MarkThielen!

Thanks @bachya for building this, great stuff !!
