### ISSUE TITLE
BUG: Using ECOWITT2MQTT_DIAGNOSTICS severely hangs the container

### ISSUE THREAD

**Issue by JvdMaat** [bachya/ecowitt2mqtt#790]
**Describe the bug**
When I enable ECOWITT2MQTT_DIAGNOSTICS=true in the container, it runs slow (UptimeKuma keeps reporting outages on reaching port 8080), and there are errors in the docker log

**To Reproduce**

1. Add ECOWITT2MQTT_DIAGNOSTICS=true
2. See error in docker logs

**Expected behavior**
Normal running with additional logging

**Screenshots**
```

2023-11-21 16:22:41,426 | DEBUG | Calculator found for interval: <ecowitt2mqtt.helpers.calculator.time.UpdateIntervalCalculator object at 0x7efd1608e650> (key: interval, value: 16.0)
2023-11-21 16:22:41,427 | DEBUG | Relative Strain Index is only valid for temperatures above 26°C and below 35°C
2023-11-21 16:22:41,427 | DEBUG | Relative Strain Index is only valid for temperatures above 26°C and below 35°C
2023-11-21 16:22:41,427 | DEBUG | Safe exposure only valid for non-zero UV indices (current: {'runtime': 182977.0, 'tempin': 69.1, 'humidityin': 52.0, 'baromrel': 30.434, 'baromabs': 30.144, SNIP
2023-11-21 16:22:41,429 | DEBUG | Wind Chill Temperature is only defined for temperatures at or below 50 F and wind speeds above 3 mph. (current temperature: 35.2, current wind speed: 0.0)
2023-11-21 16:22:41,429 | DEBUG | Publishing discovery info for 771SNIPF9FB_runtime
SNIP
2023-11-21 16:22:41,453 | DEBUG | Publishing discovery info for 7719ASNIPF9FB_windchill
2023-11-21 16:22:41,454 | DEBUG | Sending PUBLISH (d0, q0, r1, m1), 'b'homeassistant/sensor/771SNIP9FB/runtime/config'', ... (830 bytes)
SNIP
2023-11-21 16:22:41,537 | DEBUG | Sending PUBLISH (d0, q0, r0, m312), 'b'homeassistant/sensor/771SNIPF9FB/windchill/state'', ... (4 bytes)
2023-11-21 16:22:41,547 | INFO | Published to Home Assistant MQTT Discovery
2023-11-21 16:22:41,547 | DEBUG | Published data: {'runtime': CalculatedDataPoint(data_point_key='runtime', value=182977.0, unit='s', attributes={}, data_type=<DataPointType.NON_BOOLEAN: SNIP CalculatedDataPoint(data_point_key='windchill', value=None, unit='°F', attributes={}, data_type=<DataPointType.NON_BOOLEAN: 2>)}
2023-11-21 16:22:41,548 | INFO | *** DIAGNOSTICS COLLECTED
2023-11-21 16:22:41,548 | DEBUG | Stopping runtime
ERROR:    Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 71, in async_start
    await self.runtime.async_start()
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 186, in async_start
    await self._rest_api_server_task
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 81, in serve
    await self.main_loop()
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 232, in main_loop
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/venv/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
2023-11-21 16:22:41,552 | DEBUG | Sending DISCONNECT
Traceback (most recent call last):
  File "/venv/bin/ecowitt2mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/__main__.py", line 450, in main
    uvloop.run(ecowitt.async_start())
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 71, in async_start
    await self.runtime.async_start()
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 186, in async_start
    await self._rest_api_server_task
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 81, in serve
    await self.main_loop()
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 232, in main_loop
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
2023-11-21 16:23:43,181 | DEBUG | Input CLI options/environment variables: {'config': '/config/config.yaml', 'diagnostics': 'true', 'hass_discovery': 'true', 'mqtt_broker': 'mqtt.domain.com', 'mqtt_password': 'pwd', 'mqtt_username': 'user', 'verbose': True}
SNIP
2023-11-21 16:23:43,184 | INFO | Starting ecowitt2mqtt (version 2023.11.1)
2023-11-21 16:23:43,184 | DEBUG | Starting runtime
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2023-11-21 16:23:44,993 | DEBUG | Received data payload: {'PASSKEY': 'E262SNIPE1F4', 'stationtype': 'GW1100B_V2.2.7', 'runtime': '3894991', 'dateutc': '2023-11-21 21:23:44', 'tempinf': '62.60', 'humidityin': '54', 'baromrelin': '30.469', 'baromabsin': '30.150', 'tempf': '35.42', 'humidity': '68', 'winddir': '136', 'windspeedmph': '1.12', 'windgustmph': '1.34', 'maxdailygust': '10.74', 'solarradiation': '0.47', 'uv': '0', 'rainratein': '0.000', 'eventrainin': '0.000', 'hourlyrainin': '0.000', 'dailyrainin': '0.000', 'weeklyrainin': '0.004', 'monthlyrainin': '0.622', 'yearlyrainin': '30.240', 'totalrainin': '30.240', 'rrain_piezo': '0.000', 'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.413', 'yrain_piezo': '21.134', 'ws90cap_volt': '5.3', 'ws90_ver': '132', 'temp1f': '66.56', 'humidity1': '51', 'temp2f': '61.70', 'humidity2': '56', 'soilmoisture1': '33', 'pm25_ch1': '2.0', 'pm25_avg_24h_ch1': '5.9', 'lightning_num': '3', 'lightning': '14', 'lightning_time': '1700553234', 'leak_ch1': '0', 'wh40batt': '1.7', 'wh26batt': '0', 'batt1': '0', 'batt2': '0', 'soilbatt1': '1.7', 'pm25batt1': '5', 'wh57batt': '5', 'leakbatt1': '4', 'wh90batt': '3.28', 'freq': '915M', 'model': 'GW1100B', 'interval': '16'}
2023-11-21 16:23:44,994 | DEBUG | Creating MQTT loop: adc83c0af0e7432585cadf8962e3783d
INFO:     192.168.9.33:57362 - "POST /data/report/ HTTP/1.1" 204 No Content
2023-11-21 16:23:44,996 | DEBUG | Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
2023-11-21 16:23:44,997 | DEBUG | Received CONNACK (0, 0)
2023-11-21 16:23:44,997 | DEBUG | Publishing payload: {'PASSKEY': 'E26SNIPF4', 'stationtype': 'GW1100B_V2.2.7', 'runtime': '3894991', 'dateutc': '2023-11-21 21:23:44', 'tempinf': '62.60', 'humidityin': '54', 'baromrelin': '30.469', 'baromabsin': '30.150', 'tempf': '35.42', 'humidity': '68', 'winddir': '136', 'windspeedmph': '1.12', 'windgustmph': '1.34', 'maxdailygust': '10.74', 'solarradiation': '0.47', 'uv': '0', 'rainratein': '0.000', 'eventrainin': '0.000', 'hourlyrainin': '0.000', 'dailyrainin': '0.000', 'weeklyrainin': '0.004', 'monthlyrainin': '0.622', 'yearlyrainin': '30.240', 'totalrainin': '30.240', 'rrain_piezo': '0.000', 'erain_piezo': '0.000', 'hrain_piezo': '0.000', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.413', 'yrain_piezo': '21.134', 'ws90cap_volt': '5.3', 'ws90_ver': '132', 'temp1f': '66.56', 'humidity1': '51', 'temp2f': '61.70', 'humidity2': '56', 'soilmoisture1': '33', 'pm25_ch1': '2.0', 'pm25_avg_24h_ch1': '5.9', 'lightning_num': '3', 'lightning': '14', 'lightning_time': '1700553234', 'leak_ch1': '0', 'wh40batt': '1.7', 'wh26batt': '0', 'batt1': '0', 'batt2': '0', 'soilbatt1': '1.7', 'pm25batt1': '5', 'wh57batt': '5', 'leakbatt1': '4', 'wh90batt': '3.28', 'freq': '915M', 'model': 'GW1100B', 'interval': '16'}
2023-11-21 16:23:44,998 | DEBUG | Calculator found for runtime: <ecowitt2mqtt.helpers.calculator.time.RuntimeCalculator object at 0x7ffb517abe50> (key: runtime, value: 3894991.0)
SNIP
2023-11-21 16:23:45,006 | DEBUG | Calculator found for interval: <ecowitt2mqtt.helpers.calculator.time.UpdateIntervalCalculator object at 0x7ffb51795d50> (key: interval, value: 16.0)
2023-11-21 16:23:45,007 | DEBUG | Relative Strain Index is only valid for temperatures above 26°C and below 35°C
2023-11-21 16:23:45,007 | DEBUG | Relative Strain Index is only valid for temperatures above 26°C and below 35°C
SNIP
2023-11-21 16:23:45,009 | DEBUG | Wind Chill Temperature is only defined for temperatures at or below 50 F and wind speeds above 3 mph. (current temperature: 35.42, current wind speed: 1.12)
2023-11-21 16:23:45,009 | DEBUG | Publishing discovery info for E26SNIPF4_runtime
SNIP
2023-11-21 16:23:45,031 | DEBUG | Publishing discovery info for E26SNIP1F4_windchill
2023-11-21 16:23:45,032 | DEBUG | Sending PUBLISH (d0, q0, r1, m1), 'b'homeassistant/sensor/E26SNIP1F4/runtime/config'', ... (812 bytes)
SNIP
2023-11-21 16:23:45,113 | DEBUG | Sending PUBLISH (d0, q0, r0, m296), 'b'homeassistant/sensor/E2SNIP1F4/windchill/state'', ... (4 bytes)
2023-11-21 16:23:45,127 | INFO | Published to Home Assistant MQTT Discovery
2023-11-21 16:23:45,127 | DEBUG | Published data: {'runtime': CalculatedDataPoint(data_point_key='runtime', value=3894991.0, unit='s', attributes={}, data_type=<DataPointType.NON_BOOLEAN: SNIP
CalculatedDataPoint(data_point_key='windchill', value=None, unit='°F', attributes={}, data_type=<DataPointType.NON_BOOLEAN: 2>)}
2023-11-21 16:23:45,128 | INFO | *** DIAGNOSTICS COLLECTED
2023-11-21 16:23:45,129 | DEBUG | Stopping runtime
ERROR:    Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 71, in async_start
    await self.runtime.async_start()
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 186, in async_start
    await self._rest_api_server_task
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 81, in serve
    await self.main_loop()
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 232, in main_loop
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/venv/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
2023-11-21 16:23:45,133 | DEBUG | Sending DISCONNECT
Traceback (most recent call last):
  File "/venv/bin/ecowitt2mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/__main__.py", line 450, in main
    uvloop.run(ecowitt.async_start())
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/venv/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/core.py", line 71, in async_start
    await self.runtime.async_start()
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 186, in async_start
    await self._rest_api_server_task
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 81, in serve
    await self.main_loop()
  File "/venv/lib/python3.11/site-packages/uvicorn/server.py", line 232, in main_loop
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```
The above shows what 2 ecowitt devices uploading data looks like. It shows the tail end of one uploading to MQTT, and then the container "crashing", and starting back up about a minute later and the next one reports in.

**Additional context**
This shows the sequence without the errors. It stops the runtime (then a bunch of errors) and then starts back up
```
2023-11-21 16:22:41,548 | INFO | *** DIAGNOSTICS COLLECTED
2023-11-21 16:22:41,548 | DEBUG | Stopping runtime
2023-11-21 16:23:43,181 | DEBUG | Input CLI options/environment variables: {'config': '/config/config.yaml', 'diagnostics': 'true', 'hass_discovery': 'true', 'mqtt_broker': 'mqtt.domain.com', 'mqtt_password': 'pwd', 'mqtt_username': 'user', 'verbose': True}
SNIP
2023-11-21 16:23:43,184 | INFO | Starting ecowitt2mqtt (version 2023.11.1)
2023-11-21 16:23:43,184 | DEBUG | Starting runtime
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

**Comment by JvdMaat** [comment]
Is there a #pr791 image I can pull to test with?

**Comment by bachya** [comment]
@JvdMaat Yes—once the images are done [building](https://github.com/bachya/ecowitt2mqtt/actions/runs/6950122607/job/18909706632), you can pull the `pr-791` tag.

**Comment by JvdMaat** [comment]
Working like a charm!
