### ISSUE TITLE
Container crashes every few hours

### ISSUE THREAD

**Issue by mplogas** [bachya/ecowitt2mqtt#862]
**Describe the bug**
the ecowitt2mqtt containers dies every few hours, with the error message further below

**To Reproduce**

1. provide config
```yaml
battery_override:
  battery_key1: percentage
default_battery_strategy: numeric
diagnostics: false
disable_calculated_data: false
endpoint: /data/report
hass_discovery: true
hass_discovery_prefix: homeassistant
hass_entity_id_prefix: ecowitt
input_data_format: ecowitt
input_unit_system: metric
mqtt_broker: <redacted>
mqtt_password: <redacted>
mqtt_port: 1883
mqtt_retain: false
mqtt_tls: false
mqtt_topic: ecowitt
mqtt_username: <redacted>
output_unit_system: metric
port: 8080
raw_data: false
```

2. start docker container ```docker run -d --network docker-dmz --mount source=ecowitt2mqtt,target=/ecowitt -e ECOWITT2MQTT_CONFIG=/ecowitt/config.yml -p 8080:8080 --name ecowitt2mqtt bachya/ecowitt2mqtt:latest```

3. start receiving json via MQTT 
```json
{"runtime": 398839.0, "tempin": 41.54, "humidityin": 80.0, "baromrel": 1004.9108290211916, "baromabs": 1004.9108290211916, "temp": 41.0, "humidity": 97.0, "winddir": 179.0, "windspeed": 1.07826048, "windgust": 9.366382080000001, "maxdailygust": 12.9552192, "solarradiation": 29.48, "uv": 0.0, "rainrate": 1.1938, "eventrain": 5.7912, "hourlyrain": 1.7018000000000002, "dailyrain": 5.7912, "weeklyrain": 5.7912, "monthlyrain": 37.0078, "yearlyrain": 1054.1, "totalrain": 1054.1, "lightning_num": 0.0, "lightning": 24.0, "lightning_time": "2024-01-21T16:14:31+00:00", "wh65batt": "OFF", "wh57batt": 60.0, "beaufortscale": 0, "dewpoint": 40.4260933275512, "feelslike": 111.63061628755568, "frostpoint": 34.224955390910964, "frostrisk": "No risk", "heatindex": 111.63061628755568, "humidex": 79, "humidex_perception": "Dangerous", "humidityabs": 52.2004038184543, "humidityabsin": 52.2004038184543, "relative_strain_index": null, "relative_strain_index_perception": null, "safe_exposure_time_skin_type_1": null, "safe_exposure_time_skin_type_2": null, "safe_exposure_time_skin_type_3": null, "safe_exposure_time_skin_type_4": null, "safe_exposure_time_skin_type_5": null, "safe_exposure_time_skin_type_6": null, "simmerindex": 66.16243, "simmerzone": "Circulatory collapse imminent", "solarradiation_perceived": 71.43800775793144, "thermalperception": "Severely high", "windchill": null}
```

4. container crashes sometime later

Hardware:
- Froggit DP1500 Pro
- Froggit WH3000SE All-In-One sensor
- various other sensors, such as DP100 and DP60

**Expected behavior**
container is not crashing

**Logs**
```
2024-01-21 22:33:57,055 | ERROR | Exception caused a shutdown: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 128, in create_loop
    await asyncio.gather(*tasks)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/publisher/mqtt/hass.py", line 554, in async_publish
    processed_data = ProcessedData(self._config, data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 307, in __post_init__
    self._process_calculated_data_points(normalized_payload)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 323, in _process_calculated_data_points
    self.output[key] = calculator.calculate_from_payload(payload)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/__init__.py", line 207, in wrapper
    return func(calculator, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/temperature.py", line 559, in calculate_from_payload
    [rating] = [
      
    ^^^^^^^^
ValueError: not enough values to unpack (expected 1, got 0)
```

**Additional context**

**Comment by bachya** [comment]
Is the JOSN payload provided above what occurs right before the crash?

**Comment by mplogas** [comment]
I'm afraid not. I could turn on retention to get the last message, but according to the logs it seems to be caused by the calculation class - so prior to message emmision.

**Comment by bachya** [comment]
Even if that's the case, turning on verbose logging will log the incoming payload before the crash happens. That will help me determine what date of value is causing it.

**Comment by mplogas** [comment]
got it, turned on verbose logging and will report back.

**Comment by bachya** [comment]
One thing I'm noticing from your (processed) JSON payload above:

```json
{
  "runtime": 398839.0,
  "tempin": 41.54,
  "humidityin": 80.0,
  "baromrel": 1004.9108290211916,
  "baromabs": 1004.9108290211916,
  "temp": 41.0,
  "humidity": 97.0,
  "winddir": 179.0,
  "windspeed": 1.07826048,
  "windgust": 9.366382080000001,
  "maxdailygust": 12.9552192,
  "solarradiation": 29.48,
  "uv": 0.0,
  "rainrate": 1.1938,
  "eventrain": 5.7912,
  "hourlyrain": 1.7018000000000002,
  "dailyrain": 5.7912,
  "weeklyrain": 5.7912,
  "monthlyrain": 37.0078,
  "yearlyrain": 1054.1,
  "totalrain": 1054.1,
  "lightning_num": 0.0,
  "lightning": 24.0,
  "lightning_time": "2024-01-21T16:14:31+00:00",
  "wh65batt": "OFF",
  "wh57batt": 60.0,
  "beaufortscale": 0,
  "dewpoint": 40.4260933275512,
  "feelslike": 111.63061628755568,
  "frostpoint": 34.224955390910964,
  "frostrisk": "No risk",
  "heatindex": 111.63061628755568,
  "humidex": 79,
  "humidex_perception": "Dangerous",
  "humidityabs": 52.2004038184543,
  "humidityabsin": 52.2004038184543,
  "relative_strain_index": null,
  "relative_strain_index_perception": null,
  "safe_exposure_time_skin_type_1": null,
  "safe_exposure_time_skin_type_2": null,
  "safe_exposure_time_skin_type_3": null,
  "safe_exposure_time_skin_type_4": null,
  "safe_exposure_time_skin_type_5": null,
  "safe_exposure_time_skin_type_6": null,
  "simmerindex": 66.16243,
  "simmerzone": "Circulatory collapse imminent",
  "solarradiation_perceived": 71.43800775793144,
  "thermalperception": "Severely high",
  "windchill": null
}
```

You've specified the following unit configuration options (indicating that you expect metric input _and_ output units):

```yaml
input_unit_system: metric
output_unit_system: metric
```

 If that's the case, several output values look incorrect. For example, do you have an internal temperature (`tempin`) of 41.54°C (or 106.772°F)? Look at the value of `humidex` (`Dangerous`) and `simmerzone` (`Circulatory collapse imminent`). I assume you're not actually in any dire straits at the moment? 😉

Although I've never used Froggit gear, I'm guessing that, like the Ecowitt and Ambient Weather gear I've seen, it reports its data in imperial, not metric. Because you've configured `ecowitt2mqtt` to interpret input data in metric, you're seeing that exception because we have no knowledge of a relative strain index at such improbable temperatures:

https://github.com/bachya/ecowitt2mqtt/blob/89893c301f538e92ec155557e3e3051ce11ca67c/ecowitt2mqtt/helpers/calculator/temperature.py#L116-L142

**So, a quick test-fix would be to see your unit system parameters like this:**

```yaml
input_unit_system: imperial
output_unit_system: metric
```

**Comment by mplogas** [comment]
debug crash log
```
2024-01-24 05:22:10,563 | DEBUG | Calculator found for humidity: <ecowitt2mqtt.helpers.calculator.humidity.RelativeHumidityCalculator object at 0x7feffa50bdd0> (key: humidity, value: 99.0)
2024-01-24 05:22:10,563 | DEBUG | Calculator found for winddir: <ecowitt2mqtt.helpers.calculator.wind.WindDirCalculator object at 0x7feffa50ab90> (key: winddir, value: 138.0)
2024-01-24 05:22:10,564 | DEBUG | Calculator found for windspeed: <ecowitt2mqtt.helpers.calculator.wind.WindSpeedCalculator object at 0x7feffa50a850> (key: windspeed, value: 0.89)
2024-01-24 05:22:10,564 | DEBUG | Calculator found for windgust: <ecowitt2mqtt.helpers.calculator.wind.WindSpeedCalculator object at 0x7feffa508b10> (key: windgust, value: 3.36)
2024-01-24 05:22:10,565 | DEBUG | Calculator found for maxdailygust: <ecowitt2mqtt.helpers.calculator.wind.WindSpeedCalculator object at 0x7feffa50afd0> (key: maxdailygust, value: 9.17)
2024-01-24 05:22:10,565 | DEBUG | Calculator found for solarradiation: <ecowitt2mqtt.helpers.calculator.illuminance.IlluminanceCalculator object at 0x7feffa50b450> (key: solarradiation, value: 0.0)
2024-01-24 05:22:10,565 | DEBUG | Calculator found for uv: <ecowitt2mqtt.helpers.calculator.uv.UVIndexCalculator object at 0x7feffa509b10> (key: uv, value: 0.0)
2024-01-24 05:22:10,566 | DEBUG | Calculator found for rainrate: <ecowitt2mqtt.helpers.calculator.precipitation.PrecipitationRateCalculator object at 0x7feffa50a4d0> (key: rainrate, value: 0.0)
2024-01-24 05:22:10,566 | DEBUG | Calculator found for eventrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa508dd0> (key: eventrain, value: 0.228)
2024-01-24 05:22:10,567 | DEBUG | Calculator found for hourlyrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa50bb90> (key: hourlyrain, value: 0.0)
2024-01-24 05:22:10,568 | DEBUG | Calculator found for dailyrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa50bc10> (key: dailyrain, value: 0.228)
2024-01-24 05:22:10,568 | DEBUG | Calculator found for weeklyrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa508bd0> (key: weeklyrain, value: 0.539)
2024-01-24 05:22:10,569 | DEBUG | Calculator found for monthlyrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa73f390> (key: monthlyrain, value: 1.768)
2024-01-24 05:22:10,570 | DEBUG | Calculator found for yearlyrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa73d1d0> (key: yearlyrain, value: 41.811)
2024-01-24 05:22:10,570 | DEBUG | Calculator found for totalrain: <ecowitt2mqtt.helpers.calculator.precipitation.AccumulatedPrecipitationCalculator object at 0x7feffa73ff50> (key: totalrain, value: 41.811)
2024-01-24 05:22:10,570 | DEBUG | Calculator found for lightning_num: <ecowitt2mqtt.helpers.calculator.lightning.LightningStrikeCountCalculator object at 0x7feffa73d190> (key: lightning_num, value: 0.0)
2024-01-24 05:22:10,571 | DEBUG | Calculator found for lightning: <ecowitt2mqtt.helpers.calculator.lightning.LightningStrikeDistanceCalculator object at 0x7feffa73fd90> (key: lightning, value: 24.0)
2024-01-24 05:22:10,571 | DEBUG | Calculator found for lightning_time: <ecowitt2mqtt.helpers.calculator.time.EpochCalculator object at 0x7feffa73ee10> (key: lightning_time, value: 1705853671.0)
2024-01-24 05:22:10,571 | DEBUG | Calculator found for wh65batt: <ecowitt2mqtt.helpers.calculator.battery.BatteryCalculator object at 0x7feffa73ee90> (key: wh65batt, value: 0.0)
2024-01-24 05:22:10,572 | DEBUG | Calculator found for wh57batt: <ecowitt2mqtt.helpers.calculator.battery.BatteryCalculator object at 0x7feffa73f410> (key: wh57batt, value: 3.0)
2024-01-24 05:22:10,573 | DEBUG | Sending DISCONNECT
2024-01-24 05:22:10,573 | ERROR | Exception caused a shutdown: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 128, in create_loop
    await asyncio.gather(*tasks)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/publisher/mqtt/hass.py", line 554, in async_publish
    processed_data = ProcessedData(self._config, data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 307, in __post_init__
    self._process_calculated_data_points(normalized_payload)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 323, in _process_calculated_data_points
    self.output[key] = calculator.calculate_from_payload(payload)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/__init__.py", line 207, in wrapper
    return func(calculator, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/temperature.py", line 498, in calculate_from_payload
    [rating] = [
      
    ^^^^^^^^
ValueError: not enough values to unpack (expected 1, got 0)
2024-01-24 05:22:10,579 | DEBUG |   File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/runtime.py", line 128, in create_loop
    await asyncio.gather(*tasks)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/publisher/mqtt/hass.py", line 554, in async_publish
    processed_data = ProcessedData(self._config, data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 307, in __post_init__
    self._process_calculated_data_points(normalized_payload)
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/data.py", line 323, in _process_calculated_data_points
    self.output[key] = calculator.calculate_from_payload(payload)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/__init__.py", line 207, in wrapper
    return func(calculator, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ecowitt2mqtt/helpers/calculator/temperature.py", line 498, in calculate_from_payload
    [rating] = [
      
    ^^^^^^^^
2024-01-24 05:22:10,579 | DEBUG | Stopping runtime
INFO:     Shutting down
INFO:     Waiting for application shutdown.
2024-01-24 05:22:10,775 | DEBUG | Runtime shutdown complete
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
```

As for imperial/metric: good catch! I haven't looked into the values yet, but you're clearly right. I'll change that accordingly.

**Comment by bachya** [comment]
@mplogas Great! I'm going to close this issue as resolved, but if you find the crash continues to occur after the unit change, post back here and we'll re-open it.
