### ISSUE TITLE
Not possible to deploy an arm and arm64 

### ISSUE THREAD

**Issue by reba0** [bachya/ecowitt2mqtt#93]
**ecowitt2mqtt version**
latest 

**Describe the bug**
Raspi. upgraded to the last available Software 
Building is not possible  tried on raspi arm and arm64 
docker-compose deployment stops working afterwards 

**To Reproduce**

```
pi@test $ docker-compose up -d
Building ecowitt2mqtt
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.21.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1052, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1048, in up
    silent=options.get('--quiet-pull'),
  File "/usr/lib/python3/dist-packages/compose/project.py", line 466, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in ensure_image_exists
    self.build()
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1027, in build
    platform=platform,
  File "/usr/lib/python3/dist-packages/docker/api/build.py", line 154, in build
    path, exclude=exclude, dockerfile=dockerfile, gzip=gzip
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 30, in tar
    files=sorted(exclude_paths(root, exclude, dockerfile=dockerfile[0])),
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 49, in exclude_paths
    return set(pm.walk(root))
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 214, in rec_walk
    for sub in rec_walk(cur):
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/docker/utils/build.py", line 184, in rec_walk
    for f in os.listdir(current_dir):
PermissionError: [Errno 13] Permission denied: '/home/pi/IOTstack/volumes/influxdb/data/data/openhab_db'
```

docker Compose File : 

```
  ecowitt2mqtt:
    build: .
    container_name: ecowitt2mqtt
    image: bachya/ecowitt2mqtt:latest
    restart: unless-stopped
    hostname: ecowitt2mqtt
    depends_on:
      - mosquitto
    #ports:
    #  - "8053:8050/tcp"
    environment:
      #- LOG_LEVEL=DEBUG
      - LOG_LEVEL=INFO
      - ENDPOINT=/data/report
      - HASS_DISCOVERY="false"
      - PORT= 8050
      - MQTT_BROKER=mosquitto
      - MQTT_PORT= 1883
      - MQTT_USERNAME=ecowitt2mqtt
      - MQTT_PASSWORD=ecowitt2mqtt
      - MQTT_TOPIC=EFWS2900/
      - UNIT_SYSTEM=metric
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ecowitt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.ecowitt.entrypoints=tcp"
      - "traefik.tcp.services.ecowitt.loadbalancer.server.port=8050"
```

Many tanks for help

**Comment by bachya** [comment]
That stacktrace doesn't show anything related to ecowitt2mqtt. The last line is telling:

```
PermissionError: [Errno 13] Permission denied: '/home/pi/IOTstack/volumes/influxdb/data/data/openhab_db'
```

You need to fix that permissions issue.

**Comment by reba0** [comment]
All others Application, around 15 are working. All these happens as soon as i make docker-compose up -d ecowitt2mqtt. 
Not shure why that happen 
Docker himselv  works as root and has the permission. Exept if you use a different user internal in the container to build it up 
It has something to with that container. As i said i was trying it on two different raspies 

Best regards 
Reto

**Comment by bachya** [comment]
```yaml
 ecowitt2mqtt:
    build: .
    container_name: ecowitt2mqtt
    image: bachya/ecowitt2mqtt:latest
    ...
```

The inclusion of both a `build` and `image` argument here doesn't make sense; the `build .` argument indicates that the ecowitt2mqtt Docker image is in the same directory as the `docker-compose.yml` file. Why not just use the image that's already available on Docker Hub?

**Comment by reba0** [comment]
Hi Aron 
Many thanks for your feedback 
That was it !
Sorry, copiet from your github the configuration and did not study much 

Thanks again for your help 
Best regards 
Reto
