### ISSUE TITLE
Not Implemented Error when running EcoWitt2Mqtt

### ISSUE THREAD

**Issue by Frenchie90-alt** [bachya/ecowitt2mqtt#94]
Hi,

I'm getting the following error when I get to the stage of running Python app.  I've attempted to debug the app locally to no avail, I'm think there may be something I missed in the setup of HASS as that step in your documentation is a little vague:

"Once Home Assistant is configured to accept MQTT Discovery" 

I made sure the MQTT Discovery was set to enabled, and I have my MQTT Broker installed and setup, which is currently configured with another device working fine (config for MQTT Broker below). It could simply be my device is not supported, in which case I'd be happy to add it if your busy etc.

```
logins: []
customize:
  active: true
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

Error reported in console from EcoWitt2MQTT app:

```
INFO:ecowitt2mqtt:Unknown device; please report it at https://github.com/bachya/ecowitt2mqtt (payload: {'PASSKEY': '3A0CA3A42157F6147F3E3EDD630BBC60', 'stationtype': 'EasyWeatherV1.5.9', 'dateutc': '2021-10-04 02:28:32', 'tempinf': '64.4', 'humidityin': '72', 'baromrelin': '28.196', 'baromabsin': '28.196', 'tempf': '50.9', 'humidity': '96', 'winddir': '289', 'winddir_avg10m': '282', 'windspeedmph': '2.7', 'windspdmph_avg10m': '2.5', 'windgustmph': '6.9', 'maxdailygust': '20.6', 'rainratein': '0.000', 'eventrainin': '0.134', 'hourlyrainin': '0.012', 'dailyrainin': '0.134', 'weeklyrainin': '0.134', 'monthlyrainin': '1.110', 'yearlyrainin': '11.610', 'solarradiation': '174.81', 'uv': '1', 'temp1f': '66.4', 'humidity1': '69', 'soilmoisture1': '22', 'pm25_ch1': '7.0', 'pm25_avg_24h_ch1': '14.3', 'wh65batt': '0', 'wh25batt': '0', 'batt1': '0', 'soilbatt1': '1.5', 'pm25batt1': '5', 'freq': '433M', 'model': 'PT-HP2550_Pro_V1.6.7'})
ERROR:ecowitt2mqtt:Caught exception in on_socket_open:
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\aiohttp\web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "c:\python38\lib\site-packages\aiohttp\web_app.py", line 499, in _handle
    resp = await handler(request)
  File "c:\python38\lib\site-packages\ecowitt2mqtt\mqtt.py", line 106, in async_publish_payload
    await _async_publish_to_hass_discovery(client, data, discovery_manager)
  File "c:\python38\lib\site-packages\ecowitt2mqtt\mqtt.py", line 32, in _async_publish_to_hass_discovery
    async with client:
  File "c:\python38\lib\site-packages\asyncio_mqtt\client.py", line 315, in __aenter__
    await self.connect()
  File "c:\python38\lib\site-packages\asyncio_mqtt\client.py", line 78, in connect
    self._client.connect(self._hostname, self._port, 60)
  File "c:\python38\lib\site-packages\paho\mqtt\client.py", line 941, in connect
    return self.reconnect()
  File "c:\python38\lib\site-packages\paho\mqtt\client.py", line 1117, in reconnect
    self._call_socket_open()
  File "c:\python38\lib\site-packages\paho\mqtt\client.py", line 2071, in _call_socket_open
    self.on_socket_open(self, self._userdata, self._sock)
  File "c:\python38\lib\site-packages\asyncio_mqtt\client.py", line 293, in _on_socket_open
    self._loop.add_reader(sock.fileno(), cb)
  File "c:\python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
INFO:aiohttp.access:192.168.10.137 [04/Oct/2021:02:28:38 +0000] "POST /data/report HTTP/1.1" 500 250 "-" "-"
```

**Comment by bachya** [comment]
Hi @Frenchie90-alt – thanks for this. Looks like there are two things going on:

1. As you've noted, `ecowitt2mqtt` doesn't know about your device yet. Not a problem: I'm happy to add support via a PR.
2. Your `NotImplementedError` doesn't directly relate to `ecowitt2mqtt`'s code; I don't raise that exception anywhere. Looks like it's happening deeper in your stack.

I just tried this on macOS using the `dev` branch and everything worked fine. What OS, library version, etc. are you using?

**Comment by Frenchie90-alt** [comment]
Hi  @bachya ,

Can confirm that fixed the device unrecognised issued, the other still exists when running via the PIP install method, however running via Docker works perfectly.

Really appreciate the quick turn around and the work you put into this. 

Thanks again,
Eric
